/* ИНДУСТРИЯ ЗДОРОВЬЯ — interface strings (RU / UZ) */
window.I18N = {
  ru: {
    code: "RU",
    // utility bar
    delivery_all_uz: "Доставка по всему Узбекистану",
    office_addr: "100069, Ташкент, Узбекистан, ул. МКАД, д. 16",
    office_hours: "Пн–Пт, 8:00–17:00 (без перерывов)",
    warehouse_addr: "100069, Ташкент, Узбекистан, ул. МКАД, д. 16",
    warehouse_docs: "Выписка документов: пн–пт, 8:00–16:30",
    warehouse_shipment: "Отгрузка: пн–пт, 8:00–17:00 (без перерывов)",
    for_suppliers: "Поставщикам",
    service_center: "Сервис-центр",
    about: "О компании",
    contacts: "Контакты",
    login: "Войти",
    region: "Ташкент",
    // search
    search_ph: "Поиск по 2 800+ наименованиям оборудования…",
    search_btn: "Найти",
    catalog: "Каталог оборудования",
    all_categories: "Все направления",
    // header actions
    compare: "Сравнение",
    wishlist: "Избранное",
    cart: "Корзина",
    // nav quick links
    nav_promo: "Акции",
    nav_instock: "В наличии",
    nav_brands: "Бренды",
    nav_service: "Сервис и гарантия",
    nav_quote: "Запросить КП",
    // stock
    in_stock: "В наличии",
    on_order: "Под заказ",
    preorder: "Ожидается поставка",
    // product / actions
    buy: "В корзину",
    in_cart: "В корзине",
    details: "Подробнее",
    add_compare: "К сравнению",
    sku: "Арт.",
    from: "от",
    currency: "сум",
    request_price: "Запросить цену",
    per_unit: "за ед.",
    // hero
    hero_kicker: "B2B-платформа медицинского оборудования",
    hero_title_1: "Медицинское оборудование",
    hero_title_2: "для клиник и закупок",
    hero_sub: "2 800+ наименований, бренды-производители, наличие, документы, КП для закупок и доставка по Узбекистану.",
    hero_cta_catalog: "Открыть каталог",
    hero_cta_quote: "Получить КП",
    hero_cta_note: "Ответим в течение 15 минут в рабочее время",
    hero_b1: "B2B-платформа",
    hero_b2: "КП для тендеров и закупок",
    hero_b3: "Менеджеры на связи",
    hero_b4: "Доставка по Узбекистану",
    hero_stat_1: "наименований",
    hero_stat_2: "брендов-производителей",
    hero_stat_3: "регионов доставки",
    hero_stat_4: "лет на рынке",
    // sections
    sec_directions: "Каталог по направлениям",
    sec_directions_sub: "Подберите оборудование под профиль вашего отделения",
    sec_featured: "Часто закупают клиники",
    sec_featured_sub: "Популярное оборудование в наличии на складе в Ташкенте",
    sec_instock: "Оборудование в наличии на складе",
    sec_brands: "Бренды и заводы-производители",
    sec_brands_sub: "Официальные поставки и гарантия производителя",
    view_all: "Смотреть все",
    items_count: "позиций",
    // trust
    trust_title: "Почему ИНДУСТРИЯ ЗДОРОВЬЯ",
    trust_1_t: "Прямые поставки",
    trust_1_d: "Контракты напрямую с заводами-изготовителями — без посредников и наценок.",
    trust_2_t: "Сертификация",
    trust_2_d: "Полный пакет регистрационных удостоверений Минздрава РУз на каждую позицию.",
    trust_3_t: "Монтаж и сервис",
    trust_3_d: "Собственный инженерный центр: пусконаладка, обучение, гарантийное обслуживание.",
    trust_4_t: "Доставка по РУз",
    trust_4_d: "Отгрузка со склада в Ташкенте, доставка во все 14 регионов республики.",
    // cta band
    cta_title: "Комплексное оснащение «под ключ»",
    cta_sub: "Проектируем и поставляем оборудование для целых отделений и клиник. Подготовим коммерческое предложение за 1 рабочий день.",
    cta_btn: "Оставить заявку",
    cta_phone: "+998 71 200-70-70",
    // footer
    foot_about: "ИНДУСТРИЯ ЗДОРОВЬЯ — поставщик медицинского оборудования и расходных материалов для лечебных учреждений Узбекистана.",
    foot_catalog: "Каталог",
    foot_company: "Компания",
    foot_help: "Покупателям",
    foot_contacts: "Контакты",
    foot_payment: "Оплата",
    foot_shipping: "Доставка",
    foot_warranty: "Гарантия и сервис",
    foot_docs: "Документы",
    foot_rights: "© 2026 ИНДУСТРИЯ ЗДОРОВЬЯ. Все права защищены.",
    foot_addr: "100069, Ташкент, Узбекистан, ул. МКАД, д. 16",
    // catalog page
    cat_filters: "Фильтры",
    cat_reset: "Сбросить",
    cat_brand: "Производитель",
    cat_availability: "Наличие",
    cat_price: "Цена, сум",
    cat_sort: "Сортировка",
    cat_apply: "Применить",
    found: "Найдено",
    nothing: "Ничего не найдено",
    nothing_sub: "Попробуйте изменить параметры фильтра",
    showing: "Показано",
    // product page
    tab_desc: "Описание",
    tab_specs: "Характеристики",
    tab_kit: "Комплектация",
    tab_delivery: "Доставка и оплата",
    tab_docs: "Документы",
    qty: "Количество",
    add_to_cart: "Добавить в корзину",
    request_quote: "Запросить КП",
    guarantees: "Гарантии",
    g_warranty: "Гарантия 24 месяца",
    g_original: "Оригинальная продукция",
    g_install: "Монтаж и обучение",
    g_cert: "Рег. удостоверение МЗ РУз",
    related: "С этим товаром покупают",
    breadcrumb_home: "Главная",
    spec_country: "Страна",
    spec_brand: "Производитель",
    spec_warranty: "Гарантия",
    spec_reg: "Рег. удостоверение",
    desc_lead: "Поставляется официально, с полным пакетом документов и гарантией производителя.",
    // cart
    cart_title: "Корзина",
    cart_empty: "Корзина пуста",
    cart_empty_sub: "Добавьте оборудование из каталога, чтобы оформить заявку",
    cart_to_catalog: "Перейти в каталог",
    cart_item: "Товар",
    cart_price: "Цена",
    cart_qty: "Кол-во",
    cart_sum: "Сумма",
    cart_subtotal: "Товары",
    cart_total: "Итого",
    cart_vat: "включая НДС 12%",
    cart_checkout: "Оформить заявку",
    cart_quote: "Запросить КП на корзину",
    cart_clear: "Очистить",
    cart_note: "Менеджер свяжется с вами в течение рабочего дня для подтверждения наличия и условий.",
    // compare bar
    compare_bar: "К сравнению добавлено",
    compare_open: "Открыть сравнение",
    compare_clear: "Очистить",
    // quote modal
    quote_title: "Запрос коммерческого предложения",
    quote_sub: "Заполните контакты — пришлём КП с актуальными ценами и сроками.",
    quote_org: "Организация",
    quote_name: "Контактное лицо",
    quote_phone: "Телефон",
    quote_email: "E-mail",
    quote_comment: "Комментарий",
    quote_send: "Отправить запрос",
    quote_ok_t: "Заявка отправлена",
    quote_ok_d: "Наш менеджер свяжется с вами в ближайшее время.",
    quote_close: "Готово",
    added: "Добавлено в корзину",
    also_in: "Также в разделах",
    variants: "Варианты исполнения",
    accessories: "Аксессуары и принадлежности",
    consumables_section: "Расходные материалы",
    vat_incl: "с НДС",
    vat_excl: "без НДС",
    vat_note: "НДС 12% включён в цену",
    price_on_request: "Цена по запросу",
    price_on_request_note: "Стоимость рассчитывается индивидуально под объём и комплектацию",
    bulk_title: "Оптовые цены",
    bulk_from: "от",
    bulk_unit: "ед.",
    bulk_save: "экономия",
    dir_label: "Направление",
  },
  uz: {
    code: "UZ",
    delivery_all_uz: "Butun Oʻzbekiston boʻylab yetkazib berish",
    office_addr: "100069, Toshkent, O'zbekiston, MKAD ko'ch., 16-uy",
    office_hours: "Du–Ju, 8:00–17:00 (tanaffus yo'q)",
    warehouse_addr: "100069, Toshkent, O'zbekiston, MKAD ko'ch., 16-uy",
    warehouse_docs: "Hujjat chiqarish: Du–Ju, 8:00–16:30",
    warehouse_shipment: "Ombordan chiqarish: Du–Ju, 8:00–17:00 (tanaffus yo'q)",
    for_suppliers: "Yetkazib beruvchilarga",
    service_center: "Servis markazi",
    about: "Kompaniya haqida",
    contacts: "Kontaktlar",
    login: "Kirish",
    region: "Toshkent",
    search_ph: "2 800+ uskuna nomi boʻyicha qidirish…",
    search_btn: "Qidirish",
    catalog: "Uskunalar katalogi",
    all_categories: "Barcha yoʻnalishlar",
    compare: "Taqqoslash",
    wishlist: "Saralangan",
    cart: "Savat",
    nav_promo: "Aksiyalar",
    nav_instock: "Mavjud",
    nav_brands: "Brendlar",
    nav_service: "Servis va kafolat",
    nav_quote: "Taklif soʻrash",
    in_stock: "Mavjud",
    on_order: "Buyurtma asosida",
    preorder: "Yetkazib berish kutilmoqda",
    buy: "Savatga",
    in_cart: "Savatda",
    details: "Batafsil",
    add_compare: "Taqqoslashga",
    sku: "Art.",
    from: "dan",
    currency: "soʻm",
    request_price: "Narxni soʻrash",
    per_unit: "dona uchun",
    hero_kicker: "Tibbiy uskunalar B2B platformasi",
    hero_title_1: "Tibbiy uskunalar",
    hero_title_2: "klinikalar va xaridlar uchun",
    hero_sub: "2 800+ nom, ishlab chiqaruvchi brendlar, mavjudlik, hujjatlar, xaridlar uchun taklif va Oʻzbekiston boʻylab yetkazib berish.",
    hero_cta_catalog: "Katalogni ochish",
    hero_cta_quote: "Taklif olish",
    hero_cta_note: "Ish vaqtida 15 daqiqa ichida javob beramiz",
    hero_b1: "B2B-platforma",
    hero_b2: "Tender va xaridlar uchun taklif",
    hero_b3: "Menejerlar aloqada",
    hero_b4: "Oʻzbekiston boʻylab yetkazish",
    hero_stat_1: "uskuna nomi",
    hero_stat_2: "ishlab chiqaruvchi brend",
    hero_stat_3: "yetkazish hududi",
    hero_stat_4: "yillik tajriba",
    sec_directions: "Yoʻnalishlar boʻyicha katalog",
    sec_directions_sub: "Boʻlimingiz profiliga mos uskunani tanlang",
    sec_featured: "Klinikalar ko'p xarid qiladi",
    sec_featured_sub: "Toshkentdagi omborda mavjud ommabop uskunalar",
    sec_instock: "Omborda mavjud uskunalar",
    sec_brands: "Brendlar va ishlab chiqaruvchi zavodlar",
    sec_brands_sub: "Rasmiy yetkazib berish va ishlab chiqaruvchi kafolati",
    view_all: "Barchasini koʻrish",
    items_count: "ta pozitsiya",
    trust_title: "Nega SOG’LIQ INDUSTRIYASI",
    trust_1_t: "Toʻgʻridan-toʻgʻri yetkazish",
    trust_1_d: "Zavod-ishlab chiqaruvchilar bilan bevosita shartnomalar — vositachilarsiz.",
    trust_2_t: "Sertifikatlash",
    trust_2_d: "Har bir pozitsiya uchun OʻzR SSV roʻyxatdan oʻtkazish guvohnomasi.",
    trust_3_t: "Montaj va servis",
    trust_3_d: "Oʻz muhandislik markazi: ishga tushirish, oʻqitish, kafolatli xizmat.",
    trust_4_t: "OʻzR boʻylab yetkazish",
    trust_4_d: "Toshkent omboridan joʻnatish, respublikaning 14 hududiga yetkazish.",
    cta_title: "«Kalit topshirish» asosida kompleks jihozlash",
    cta_sub: "Butun boʻlim va klinikalar uchun uskunalar loyihalaymiz va yetkazamiz. 1 ish kunida tijorat taklifini tayyorlaymiz.",
    cta_btn: "Ariza qoldirish",
    cta_phone: "+998 71 200-70-70",
    foot_about: "SOG’LIQ INDUSTRIYASI — Oʻzbekiston davolash muassasalari uchun tibbiy uskunalar va sarf materiallari yetkazib beruvchi.",
    foot_catalog: "Katalog",
    foot_company: "Kompaniya",
    foot_help: "Xaridorlarga",
    foot_contacts: "Kontaktlar",
    foot_payment: "Toʻlov",
    foot_shipping: "Yetkazib berish",
    foot_warranty: "Kafolat va servis",
    foot_docs: "Hujjatlar",
    foot_rights: "© 2026 SOG’LIQ INDUSTRIYASI. Barcha huquqlar himoyalangan.",
    foot_addr: "Toshkent sh., Mirzo-Ulugʻbek t., Mustaqillik koʻch., 75",
    cat_filters: "Filtrlar",
    cat_reset: "Tozalash",
    cat_brand: "Ishlab chiqaruvchi",
    cat_availability: "Mavjudligi",
    cat_price: "Narxi, soʻm",
    cat_sort: "Saralash",
    cat_apply: "Qoʻllash",
    found: "Topildi",
    nothing: "Hech narsa topilmadi",
    nothing_sub: "Filtr parametrlarini oʻzgartirib koʻring",
    showing: "Koʻrsatilgan",
    tab_desc: "Tavsif",
    tab_specs: "Xususiyatlari",
    tab_kit: "Toʻplam tarkibi",
    tab_delivery: "Yetkazish va toʻlov",
    tab_docs: "Hujjatlar",
    qty: "Miqdori",
    add_to_cart: "Savatga qoʻshish",
    request_quote: "Taklif soʻrash",
    guarantees: "Kafolatlar",
    g_warranty: "24 oy kafolat",
    g_original: "Original mahsulot",
    g_install: "Montaj va oʻqitish",
    g_cert: "OʻzR SSV guvohnomasi",
    related: "Bu mahsulot bilan olishadi",
    breadcrumb_home: "Bosh sahifa",
    spec_country: "Mamlakat",
    spec_brand: "Ishlab chiqaruvchi",
    spec_warranty: "Kafolat",
    spec_reg: "Roʻyxat guvohnomasi",
    desc_lead: "Toʻliq hujjatlar paketi va ishlab chiqaruvchi kafolati bilan rasmiy yetkaziladi.",
    cart_title: "Savat",
    cart_empty: "Savat boʻsh",
    cart_empty_sub: "Ariza berish uchun katalogdan uskuna qoʻshing",
    cart_to_catalog: "Katalogga oʻtish",
    cart_item: "Mahsulot",
    cart_price: "Narxi",
    cart_qty: "Soni",
    cart_sum: "Summa",
    cart_subtotal: "Mahsulotlar",
    cart_total: "Jami",
    cart_vat: "QQS 12% bilan",
    cart_checkout: "Ariza berish",
    cart_quote: "Savat uchun taklif soʻrash",
    cart_clear: "Tozalash",
    cart_note: "Menejer mavjudlik va shartlarni tasdiqlash uchun ish kuni davomida bogʻlanadi.",
    compare_bar: "Taqqoslashga qoʻshildi",
    compare_open: "Taqqoslashni ochish",
    compare_clear: "Tozalash",
    quote_title: "Tijorat taklifi soʻrovi",
    quote_sub: "Kontaktlarni toʻldiring — dolzarb narx va muddatlar bilan taklif yuboramiz.",
    quote_org: "Tashkilot",
    quote_name: "Aloqa shaxsi",
    quote_phone: "Telefon",
    quote_email: "E-mail",
    quote_comment: "Izoh",
    quote_send: "Soʻrov yuborish",
    quote_ok_t: "Ariza yuborildi",
    quote_ok_d: "Menejerimiz tez orada siz bilan bogʻlanadi.",
    quote_close: "Tayyor",
    added: "Savatga qoʻshildi",
    also_in: "Shuningdek boʻlimlarda",
    variants: "Ishlash variantlari",
    accessories: "Aksessuarlar va jihozlar",
    consumables_section: "Sarf materiallar",
    vat_incl: "QQS bilan",
    vat_excl: "QQSsiz",
    vat_note: "QQS 12% narxga kiritilgan",
    price_on_request: "Narx soʻrov boʻyicha",
    price_on_request_note: "Narx hajm va jihozlanishga qarab individual hisoblanadi",
    bulk_title: "Ulgurji narxlar",
    bulk_from: "dan",
    bulk_unit: "dona",
    bulk_save: "tejash",
    dir_label: "Yoʻnalish",
  },
  en: {
    code: "EN",
    delivery_all_uz: "Delivery across Uzbekistan",
    office_addr: "100069, Tashkent, Uzbekistan, MKAD St., Bldg. 16",
    office_hours: "Mon–Fri, 8:00–17:00 (no breaks)",
    warehouse_addr: "100069, Tashkent, Uzbekistan, MKAD St., Bldg. 16",
    warehouse_docs: "Document issue: Mon–Fri, 8:00–16:30",
    warehouse_shipment: "Warehouse shipment: Mon–Fri, 8:00–17:00 (no breaks)",
    for_suppliers: "For suppliers",
    service_center: "Service center",
    about: "About",
    contacts: "Contacts",
    login: "Sign in",
    region: "Tashkent",
    search_ph: "Search 2,800+ equipment items…",
    search_btn: "Search",
    catalog: "Equipment catalog",
    all_categories: "All directions",
    compare: "Compare",
    wishlist: "Wishlist",
    cart: "Cart",
    nav_promo: "Deals",
    nav_instock: "In stock",
    nav_brands: "Brands",
    nav_service: "Service & warranty",
    nav_quote: "Request a quote",
    in_stock: "In stock",
    on_order: "On order",
    preorder: "Awaiting delivery",
    buy: "Add",
    in_cart: "In cart",
    details: "Details",
    add_compare: "Compare",
    sku: "SKU",
    from: "from",
    currency: "UZS",
    request_price: "Request price",
    per_unit: "per unit",
    hero_kicker: "B2B medical equipment platform",
    hero_title_1: "Medical equipment",
    hero_title_2: "for clinics and procurement",
    hero_sub: "2,800+ items, manufacturer brands, availability, documents, quotes for procurement and delivery across Uzbekistan.",
    hero_cta_catalog: "Open catalog",
    hero_cta_quote: "Get a quote",
    hero_cta_note: "We reply within 15 minutes during business hours",
    hero_b1: "B2B platform",
    hero_b2: "Quotes for tenders & procurement",
    hero_b3: "Managers online",
    hero_b4: "Delivery across Uzbekistan",
    hero_stat_1: "equipment items",
    hero_stat_2: "manufacturer brands",
    hero_stat_3: "delivery regions",
    hero_stat_4: "years on the market",
    sec_directions: "Catalog by direction",
    sec_directions_sub: "Find equipment matching your department's profile",
    sec_featured: "Frequently bought by clinics",
    sec_featured_sub: "Popular equipment in stock at the Tashkent warehouse",
    sec_instock: "Equipment in stock",
    sec_brands: "Brands & manufacturers",
    sec_brands_sub: "Official supplies and manufacturer's warranty",
    view_all: "View all",
    items_count: "items",
    trust_title: "Why HEALTH INDUSTRY",
    trust_1_t: "Direct supplies",
    trust_1_d: "Contracts directly with manufacturing plants — no intermediaries or markups.",
    trust_2_t: "Certification",
    trust_2_d: "Full package of MoH Uzbekistan registration certificates for every item.",
    trust_3_t: "Installation & service",
    trust_3_d: "In-house engineering center: commissioning, training, warranty service.",
    trust_4_t: "Delivery across Uzbekistan",
    trust_4_d: "Shipping from the Tashkent warehouse to all 14 regions of the republic.",
    cta_title: "Turnkey complex equipping",
    cta_sub: "We design and supply equipment for entire departments and clinics. We'll prepare a quote within 1 business day.",
    cta_btn: "Submit a request",
    cta_phone: "+998 71 200-70-70",
    foot_about: "HEALTH INDUSTRY — supplier of medical equipment and consumables for healthcare institutions in Uzbekistan.",
    foot_catalog: "Catalog",
    foot_company: "Company",
    foot_help: "For buyers",
    foot_contacts: "Contacts",
    foot_payment: "Payment",
    foot_shipping: "Delivery",
    foot_warranty: "Warranty & service",
    foot_docs: "Documents",
    foot_rights: "© 2026 HEALTH INDUSTRY. All rights reserved.",
    foot_addr: "Tashkent, Mirzo-Ulugbek district, Mustakillik st., 75",
    cat_filters: "Filters",
    cat_reset: "Reset",
    cat_brand: "Manufacturer",
    cat_availability: "Availability",
    cat_price: "Price, UZS",
    cat_sort: "Sort",
    cat_apply: "Apply",
    found: "Found",
    nothing: "Nothing found",
    nothing_sub: "Try changing the filter parameters",
    showing: "Showing",
    tab_desc: "Description",
    tab_specs: "Specifications",
    tab_kit: "Package contents",
    tab_delivery: "Delivery & payment",
    tab_docs: "Documents",
    qty: "Quantity",
    add_to_cart: "Add to cart",
    request_quote: "Request a quote",
    guarantees: "Guarantees",
    g_warranty: "24-month warranty",
    g_original: "Genuine product",
    g_install: "Installation & training",
    g_cert: "MoH Uzbekistan certificate",
    related: "Frequently bought together",
    breadcrumb_home: "Home",
    spec_country: "Country",
    spec_brand: "Manufacturer",
    spec_warranty: "Warranty",
    spec_reg: "Registration certificate",
    desc_lead: "Supplied officially, with a full package of documents and the manufacturer's warranty.",
    cart_title: "Cart",
    cart_empty: "Your cart is empty",
    cart_empty_sub: "Add equipment from the catalog to place a request",
    cart_to_catalog: "Go to catalog",
    cart_item: "Item",
    cart_price: "Price",
    cart_qty: "Qty",
    cart_sum: "Sum",
    cart_subtotal: "Items",
    cart_total: "Total",
    cart_vat: "incl. 12% VAT",
    cart_checkout: "Place request",
    cart_quote: "Request a quote for cart",
    cart_clear: "Clear",
    cart_note: "A manager will contact you within one business day to confirm availability and terms.",
    compare_bar: "Added to compare",
    compare_open: "Open comparison",
    compare_clear: "Clear",
    quote_title: "Quote request",
    quote_sub: "Fill in your contacts — we'll send a quote with current prices and lead times.",
    quote_org: "Organization",
    quote_name: "Contact person",
    quote_phone: "Phone",
    quote_email: "E-mail",
    quote_comment: "Comment",
    quote_send: "Send request",
    quote_ok_t: "Request sent",
    quote_ok_d: "Our manager will contact you shortly.",
    quote_close: "Done",
    added: "Added to cart",
    also_in: "Also in",
    variants: "Variants",
    accessories: "Accessories",
    consumables_section: "Consumables",
    vat_incl: "VAT incl.",
    vat_excl: "VAT excl.",
    vat_note: "VAT 12% included in price",
    price_on_request: "Price on request",
    price_on_request_note: "Price is calculated individually based on volume and configuration",
    bulk_title: "Bulk pricing",
    bulk_from: "from",
    bulk_unit: "pcs",
    bulk_save: "save",
    dir_label: "Specialty",
  },
};
