/* SOI — нормализованный каталог (single source of truth)
   Источник: SOI_каталог_нормализованный.xlsx
   Модель: категория → подкатегория → товарная группа (primary);
           направление → подраздел → товарная группа (many-to-many через links).
   Поле active=false → сущность скрыта на сайте (статус «Планируется»). */
(function(){
  window.SOI_CATALOG_DEFAULT = {
  categories: [
    {"id":"C01","name":"Медицинское оборудование","slug":"meditsinskoe-oborudovanie","icon":"pulse","order":1,"active":true},
    {"id":"C02","name":"Медицинская мебель","slug":"meditsinskaya-mebel","icon":"bed","order":2,"active":true},
    {"id":"C03","name":"Медицинские инструменты","slug":"meditsinskie-instrumenty","icon":"scalpel","order":3,"active":true},
    {"id":"C04","name":"Расходные материалы","slug":"rashodnye-materialy","icon":"shield-cross","order":4,"active":true}
  ],
  subcategories: [
    {"id":"S001","cat":"C01","name":"Диагностическое оборудование","slug":"diagnosticheskoe-oborudovanie","order":1,"active":true},
    {"id":"S002","cat":"C01","name":"Функциональная диагностика","slug":"funktsionalnaya-diagnostika","order":2,"active":true},
    {"id":"S003","cat":"C01","name":"Реанимационное оборудование","slug":"reanimatsionnoe-oborudovanie","order":3,"active":true},
    {"id":"S004","cat":"C01","name":"Анестезиологическое оборудование","slug":"anesteziologicheskoe-oborudovanie","order":4,"active":true},
    {"id":"S005","cat":"C01","name":"Хирургическое оборудование","slug":"hirurgicheskoe-oborudovanie","order":5,"active":true},
    {"id":"S006","cat":"C01","name":"Лабораторное оборудование","slug":"laboratornoe-oborudovanie","order":6,"active":true},
    {"id":"S007","cat":"C01","name":"Стерилизация и дезинфекция","slug":"sterilizatsiya-i-dezinfektsiya","order":7,"active":true},
    {"id":"S008","cat":"C01","name":"Стоматологическое оборудование","slug":"stomatologicheskoe-oborudovanie","order":8,"active":true},
    {"id":"S009","cat":"C01","name":"Неонатологическое оборудование","slug":"neonatologicheskoe-oborudovanie","order":9,"active":true},
    {"id":"S010","cat":"C01","name":"Офтальмологическое оборудование","slug":"oftalmologicheskoe-oborudovanie","order":10,"active":true},
    {"id":"S011","cat":"C01","name":"ЛОР-оборудование","slug":"lor-oborudovanie","order":11,"active":true},
    {"id":"S012","cat":"C01","name":"Физиотерапия и реабилитация","slug":"fizioterapiya-i-reabilitatsiya","order":12,"active":true},
    {"id":"S013","cat":"C01","name":"Рентгенология и визуализация","slug":"rentgenologiya-i-vizualizatsiya","order":13,"active":true},
    {"id":"S014","cat":"C01","name":"Эндоскопическое оборудование","slug":"endoskopicheskoe-oborudovanie","order":14,"active":true},
    {"id":"S015","cat":"C01","name":"Оборудование для скорой помощи","slug":"oborudovanie-dlya-skoroy-pomoschi","order":15,"active":true},
    {"id":"S016","cat":"C02","name":"Медицинские кровати","slug":"meditsinskie-krovati","order":16,"active":true},
    {"id":"S017","cat":"C02","name":"Кушетки и смотровые столы","slug":"kushetki-i-smotrovye-stoly","order":17,"active":true},
    {"id":"S018","cat":"C02","name":"Медицинские кресла","slug":"meditsinskie-kresla","order":18,"active":true},
    {"id":"S019","cat":"C02","name":"Медицинские столы","slug":"meditsinskie-stoly","order":19,"active":true},
    {"id":"S020","cat":"C02","name":"Тележки медицинские","slug":"telezhki-meditsinskie","order":20,"active":true},
    {"id":"S021","cat":"C02","name":"Шкафы медицинские","slug":"shkafy-meditsinskie","order":21,"active":true},
    {"id":"S022","cat":"C02","name":"Тумбы и стеллажи","slug":"tumby-i-stellazhi","order":22,"active":true},
    {"id":"S023","cat":"C02","name":"Ширмы, штативы и стойки","slug":"shirmy-shtativy-i-stoyki","order":23,"active":true},
    {"id":"S024","cat":"C02","name":"Лабораторная мебель","slug":"laboratornaya-mebel","order":24,"active":true},
    {"id":"S025","cat":"C02","name":"Мебель для кабинетов и палат","slug":"mebel-dlya-kabinetov-i-palat","order":25,"active":true},
    {"id":"S026","cat":"C03","name":"Хирургические инструменты","slug":"hirurgicheskie-instrumenty","order":26,"active":true},
    {"id":"S027","cat":"C03","name":"Акушерско-гинекологические инструменты","slug":"akushersko-ginekologicheskie-instrumenty","order":27,"active":true},
    {"id":"S028","cat":"C03","name":"Стоматологические инструменты","slug":"stomatologicheskie-instrumenty","order":28,"active":true},
    {"id":"S029","cat":"C03","name":"ЛОР-инструменты","slug":"lor-instrumenty","order":29,"active":true},
    {"id":"S030","cat":"C03","name":"Офтальмологические инструменты","slug":"oftalmologicheskie-instrumenty","order":30,"active":true},
    {"id":"S031","cat":"C03","name":"Травматологические и ортопедические инструменты","slug":"travmatologicheskie-i-ortopedicheskie-instrumenty","order":31,"active":true},
    {"id":"S032","cat":"C03","name":"Диагностические инструменты","slug":"diagnosticheskie-instrumenty","order":32,"active":true},
    {"id":"S033","cat":"C03","name":"Инструменты для процедурного кабинета","slug":"instrumenty-dlya-protsedurnogo-kabineta","order":33,"active":true},
    {"id":"S034","cat":"C03","name":"Наборы медицинских инструментов","slug":"nabory-meditsinskih-instrumentov","order":34,"active":true},
    {"id":"S035","cat":"C03","name":"Вспомогательные инструменты и принадлежности","slug":"vspomogatelnye-instrumenty-i-prinadlezhnosti","order":35,"active":true},
    {"id":"S036","cat":"C04","name":"Средства индивидуальной защиты","slug":"sredstva-individualnoy-zaschity","order":36,"active":true},
    {"id":"S037","cat":"C04","name":"Инъекционные и инфузионные материалы","slug":"inektsionnye-i-infuzionnye-materialy","order":37,"active":true},
    {"id":"S038","cat":"C04","name":"Перевязочные материалы","slug":"perevyazochnye-materialy","order":38,"active":true},
    {"id":"S039","cat":"C04","name":"Дезинфекция и антисептика","slug":"dezinfektsiya-i-antiseptika","order":39,"active":true},
    {"id":"S040","cat":"C04","name":"Стерилизационные расходные материалы","slug":"sterilizatsionnye-rashodnye-materialy","order":40,"active":true},
    {"id":"S041","cat":"C04","name":"Лабораторные расходные материалы","slug":"laboratornye-rashodnye-materialy","order":41,"active":true},
    {"id":"S042","cat":"C04","name":"Расходные материалы для диагностики","slug":"rashodnye-materialy-dlya-diagnostiki","order":42,"active":true},
    {"id":"S043","cat":"C04","name":"Реанимация и анестезиология","slug":"reanimatsiya-i-anesteziologiya","order":43,"active":true},
    {"id":"S044","cat":"C04","name":"Хирургические расходные материалы","slug":"hirurgicheskie-rashodnye-materialy","order":44,"active":true},
    {"id":"S045","cat":"C04","name":"Стоматологические расходные материалы","slug":"stomatologicheskie-rashodnye-materialy","order":45,"active":true},
    {"id":"S046","cat":"C04","name":"Гинекологические и урологические расходные материалы","slug":"ginekologicheskie-i-urologicheskie-rashodnye-materialy","order":46,"active":true},
    {"id":"S047","cat":"C04","name":"Уход за пациентами","slug":"uhod-za-patsientami","order":47,"active":true},
    {"id":"S048","cat":"C04","name":"Медицинские отходы","slug":"meditsinskie-othody","order":48,"active":true}
  ],
  directions: [
    {"id":"D01","name":"Акушерство и гинекология","slug":"akusherstvo-i-ginekologiya","priority":"B","order":1,"active":true},
    {"id":"D02","name":"Анестезиология и реанимация","slug":"anesteziologiya-i-reanimaciya","priority":"A","order":2,"active":true},
    {"id":"D03","name":"Диагностика","slug":"diagnostika","priority":"A","order":3,"active":true},
    {"id":"D04","name":"Функциональная диагностика","slug":"funkcionalnaya-diagnostika","priority":"A","order":4,"active":true},
    {"id":"D05","name":"Лаборатория","slug":"laboratoriya","priority":"A","order":5,"active":true},
    {"id":"D06","name":"Стерилизация и дезинфекция","slug":"sterilizaciya-i-dezinfekciya","priority":"A","order":6,"active":true},
    {"id":"D07","name":"Стоматология","slug":"stomatologiya","priority":"A","order":7,"active":true},
    {"id":"D08","name":"Хирургия","slug":"hirurgiya","priority":"A","order":8,"active":true},
    {"id":"D09","name":"Эндоскопия","slug":"endoskopiya","priority":"C","order":9,"active":false},
    {"id":"D10","name":"Неонатология","slug":"neonatologiya","priority":"B","order":10,"active":true},
    {"id":"D11","name":"ЛОР","slug":"lor","priority":"B","order":11,"active":true},
    {"id":"D12","name":"Офтальмология","slug":"oftalmologiya","priority":"B","order":12,"active":true},
    {"id":"D13","name":"Рентгенология и визуализация","slug":"rentgenologiya-i-vizualizaciya","priority":"C","order":13,"active":false},
    {"id":"D14","name":"Физиотерапия и реабилитация","slug":"fizioterapiya-i-reabilitaciya","priority":"B","order":14,"active":true},
    {"id":"D15","name":"Травматология и ортопедия","slug":"travmatologiya-i-ortopediya","priority":"C","order":15,"active":true},
    {"id":"D16","name":"Скорая помощь","slug":"skoraya-pomosch","priority":"B","order":16,"active":true},
    {"id":"D17","name":"Служба крови","slug":"sluzhba-krovi","priority":"C","order":17,"active":false},
    {"id":"D18","name":"Кислородотерапия","slug":"kislorodoterapiya","priority":"B","order":18,"active":true},
    {"id":"D19","name":"Иммобилизация","slug":"immobilizaciya","priority":"C","order":19,"active":true},
    {"id":"D20","name":"Косметология и дерматология","slug":"kosmetologiya-i-dermatologiya","priority":"C","order":20,"active":false},
    {"id":"D21","name":"Проктология","slug":"proktologiya","priority":"C","order":21,"active":false},
    {"id":"D22","name":"Урология","slug":"urologiya","priority":"C","order":22,"active":false},
    {"id":"D23","name":"Кардиология","slug":"kardiologiya","priority":"C","order":23,"active":true}
  ],
  sections: [
    {"id":"D01.01","dir":"D01","name":"Гинекологический кабинет","slug":"ginekologicheskiy-kabinet","order":1,"active":true},
    {"id":"D01.02","dir":"D01","name":"Акушерский приём и родильный зал","slug":"akusherskiy-priem-i-rodilnyy-zal","order":2,"active":true},
    {"id":"D01.03","dir":"D01","name":"УЗ-диагностика в акушерстве и гинекологии","slug":"uz-diagnostika-v-akusherstve-i-ginekologii","order":3,"active":true},
    {"id":"D01.04","dir":"D01","name":"Расходные материалы для гинекологии","slug":"rashodnye-materialy-dlya-ginekologii","order":4,"active":true},
    {"id":"D02.01","dir":"D02","name":"Респираторная поддержка","slug":"respiratornaya-podderzhka","order":5,"active":true},
    {"id":"D02.02","dir":"D02","name":"Мониторинг и контроль","slug":"monitoring-i-kontrol","order":6,"active":true},
    {"id":"D02.03","dir":"D02","name":"Инфузионная терапия","slug":"infuzionnaya-terapiya","order":7,"active":true},
    {"id":"D02.04","dir":"D02","name":"Расходные материалы для реанимации","slug":"rashodnye-materialy-dlya-reanimacii","order":8,"active":true},
    {"id":"D02.05","dir":"D02","name":"Мебель и инфраструктура ОРИТ","slug":"mebel-i-infrastruktura-orit","order":9,"active":true},
    {"id":"D03.01","dir":"D03","name":"Ультразвуковая диагностика","slug":"ultrazvukovaya-diagnostika","order":10,"active":true},
    {"id":"D03.02","dir":"D03","name":"Базовая диагностика","slug":"bazovaya-diagnostika","order":11,"active":true},
    {"id":"D03.03","dir":"D03","name":"Оптическая диагностика","slug":"opticheskaya-diagnostika","order":12,"active":true},
    {"id":"D03.04","dir":"D03","name":"Диагностические расходные материалы","slug":"diagnosticheskie-rashodnye-materialy","order":13,"active":true},
    {"id":"D04.01","dir":"D04","name":"ЭКГ-диагностика","slug":"ekg-diagnostika","order":14,"active":true},
    {"id":"D04.02","dir":"D04","name":"Суточный мониторинг","slug":"sutochnyy-monitoring","order":15,"active":true},
    {"id":"D04.03","dir":"D04","name":"Респираторная функциональная диагностика","slug":"respiratornaya-funkcionalnaya-diagnostika","order":16,"active":true},
    {"id":"D04.04","dir":"D04","name":"Нейрофизиология","slug":"neyrofiziologiya","order":17,"active":true},
    {"id":"D04.05","dir":"D04","name":"Нагрузочные тесты","slug":"nagruzochnye-testy","order":18,"active":true},
    {"id":"D05.01","dir":"D05","name":"Клиническая лабораторная диагностика","slug":"klinicheskaya-laboratornaya-diagnostika","order":19,"active":true},
    {"id":"D05.02","dir":"D05","name":"Общелабораторное оборудование","slug":"obschelaboratornoe-oborudovanie","order":20,"active":true},
    {"id":"D05.03","dir":"D05","name":"Холодовая цепь","slug":"holodovaya-cep","order":21,"active":true},
    {"id":"D05.04","dir":"D05","name":"Лабораторная мебель","slug":"laboratornaya-mebel","order":22,"active":true},
    {"id":"D05.05","dir":"D05","name":"Лабораторные расходные материалы","slug":"laboratornye-rashodnye-materialy","order":23,"active":true},
    {"id":"D06.01","dir":"D06","name":"Стерилизационное оборудование","slug":"sterilizacionnoe-oborudovanie","order":24,"active":true},
    {"id":"D06.02","dir":"D06","name":"Предстерилизационная очистка","slug":"predsterilizacionnaya-ochistka","order":25,"active":true},
    {"id":"D06.03","dir":"D06","name":"Дезинфекция воздуха и поверхностей","slug":"dezinfekciya-vozduha-i-poverhnostey","order":26,"active":true},
    {"id":"D06.04","dir":"D06","name":"Расходные материалы для стерилизации","slug":"rashodnye-materialy-dlya-sterilizacii","order":27,"active":true},
    {"id":"D07.01","dir":"D07","name":"Стоматологический кабинет","slug":"stomatologicheskiy-kabinet","order":28,"active":true},
    {"id":"D07.02","dir":"D07","name":"Стоматологическая диагностика","slug":"stomatologicheskaya-diagnostika","order":29,"active":true},
    {"id":"D07.03","dir":"D07","name":"Стоматологическая стерилизация","slug":"stomatologicheskaya-sterilizaciya","order":30,"active":true},
    {"id":"D07.04","dir":"D07","name":"Стоматологические инструменты","slug":"stomatologicheskie-instrumenty","order":31,"active":true},
    {"id":"D07.05","dir":"D07","name":"Стоматологические расходные материалы","slug":"stomatologicheskie-rashodnye-materialy","order":32,"active":true},
    {"id":"D08.01","dir":"D08","name":"Операционный блок","slug":"operacionnyy-blok","order":33,"active":true},
    {"id":"D08.02","dir":"D08","name":"Малая хирургия и перевязочная","slug":"malaya-hirurgiya-i-perevyazochnaya","order":34,"active":true},
    {"id":"D08.03","dir":"D08","name":"Хирургические инструменты","slug":"hirurgicheskie-instrumenty","order":35,"active":true},
    {"id":"D08.04","dir":"D08","name":"Хирургические расходные материалы","slug":"hirurgicheskie-rashodnye-materialy","order":36,"active":true},
    {"id":"D09.01","dir":"D09","name":"Эндоскопические системы","slug":"endoskopicheskie-sistemy","order":37,"active":true},
    {"id":"D09.02","dir":"D09","name":"Гибкая эндоскопия","slug":"gibkaya-endoskopiya","order":38,"active":true},
    {"id":"D09.03","dir":"D09","name":"Обработка эндоскопов","slug":"obrabotka-endoskopov","order":39,"active":true},
    {"id":"D09.04","dir":"D09","name":"Эндоскопические инструменты и расходники","slug":"endoskopicheskie-instrumenty-i-rashodniki","order":40,"active":true},
    {"id":"D10.01","dir":"D10","name":"Интенсивная терапия новорождённых","slug":"intensivnaya-terapiya-novorozhdennyh","order":41,"active":true},
    {"id":"D10.02","dir":"D10","name":"Фототерапия и обогрев","slug":"fototerapiya-i-obogrev","order":42,"active":true},
    {"id":"D10.03","dir":"D10","name":"Неонатальная мебель","slug":"neonatalnaya-mebel","order":43,"active":true},
    {"id":"D10.04","dir":"D10","name":"Расходные материалы для неонатологии","slug":"rashodnye-materialy-dlya-neonatologii","order":44,"active":true},
    {"id":"D11.01","dir":"D11","name":"ЛОР-кабинет","slug":"lor-kabinet","order":45,"active":true},
    {"id":"D11.02","dir":"D11","name":"Аудиология","slug":"audiologiya","order":46,"active":true},
    {"id":"D11.03","dir":"D11","name":"ЛОР-эндоскопия","slug":"lor-endoskopiya","order":47,"active":true},
    {"id":"D11.04","dir":"D11","name":"ЛОР-инструменты","slug":"lor-instrumenty","order":48,"active":true},
    {"id":"D12.01","dir":"D12","name":"Диагностика зрения","slug":"diagnostika-zreniya","order":49,"active":true},
    {"id":"D12.02","dir":"D12","name":"Кабинет офтальмолога","slug":"kabinet-oftalmologa","order":50,"active":true},
    {"id":"D12.03","dir":"D12","name":"Офтальмологические инструменты","slug":"oftalmologicheskie-instrumenty","order":51,"active":true},
    {"id":"D12.04","dir":"D12","name":"Расходные материалы","slug":"rashodnye-materialy","order":52,"active":true},
    {"id":"D13.01","dir":"D13","name":"Рентген-диагностика","slug":"rentgen-diagnostika","order":53,"active":true},
    {"id":"D13.02","dir":"D13","name":"Стоматологическая визуализация","slug":"stomatologicheskaya-vizualizaciya","order":54,"active":true},
    {"id":"D13.03","dir":"D13","name":"Защита и аксессуары","slug":"zaschita-i-aksessuary","order":55,"active":true},
    {"id":"D14.01","dir":"D14","name":"Физиотерапевтические аппараты","slug":"fizioterapevticheskie-apparaty","order":56,"active":true},
    {"id":"D14.02","dir":"D14","name":"Реабилитационное оборудование","slug":"reabilitacionnoe-oborudovanie","order":57,"active":true},
    {"id":"D14.03","dir":"D14","name":"Массаж и восстановление","slug":"massazh-i-vosstanovlenie","order":58,"active":true},
    {"id":"D14.04","dir":"D14","name":"Расходники и аксессуары","slug":"rashodniki-i-aksessuary","order":59,"active":true},
    {"id":"D15.01","dir":"D15","name":"Ортопедическая хирургия","slug":"ortopedicheskaya-hirurgiya","order":60,"active":true},
    {"id":"D15.02","dir":"D15","name":"Иммобилизация","slug":"immobilizaciya","order":61,"active":true},
    {"id":"D15.03","dir":"D15","name":"Реабилитация после травм","slug":"reabilitaciya-posle-travm","order":62,"active":true},
    {"id":"D16.01","dir":"D16","name":"Портативная реанимация","slug":"portativnaya-reanimaciya","order":63,"active":true},
    {"id":"D16.02","dir":"D16","name":"Транспортировка и иммобилизация","slug":"transportirovka-i-immobilizaciya","order":64,"active":true},
    {"id":"D16.03","dir":"D16","name":"Кислородная поддержка","slug":"kislorodnaya-podderzhka","order":65,"active":true},
    {"id":"D16.04","dir":"D16","name":"Укладки и расходники","slug":"ukladki-i-rashodniki","order":66,"active":true},
    {"id":"D17.01","dir":"D17","name":"Забор крови","slug":"zabor-krovi","order":67,"active":true},
    {"id":"D17.02","dir":"D17","name":"Хранение крови","slug":"hranenie-krovi","order":68,"active":true},
    {"id":"D17.03","dir":"D17","name":"Обработка и разделение","slug":"obrabotka-i-razdelenie","order":69,"active":true},
    {"id":"D18.01","dir":"D18","name":"Источники кислорода","slug":"istochniki-kisloroda","order":70,"active":true},
    {"id":"D18.02","dir":"D18","name":"Подача кислорода пациенту","slug":"podacha-kisloroda-pacientu","order":71,"active":true},
    {"id":"D18.03","dir":"D18","name":"Неинвазивная вентиляция","slug":"neinvazivnaya-ventilyaciya","order":72,"active":true},
    {"id":"D19.01","dir":"D19","name":"Транспортная иммобилизация","slug":"transportnaya-immobilizaciya","order":73,"active":true},
    {"id":"D19.02","dir":"D19","name":"Ортопедическая фиксация","slug":"ortopedicheskaya-fiksaciya","order":74,"active":true},
    {"id":"D20.01","dir":"D20","name":"Дерматологическая диагностика","slug":"dermatologicheskaya-diagnostika","order":75,"active":true},
    {"id":"D20.02","dir":"D20","name":"Косметологическое оборудование","slug":"kosmetologicheskoe-oborudovanie","order":76,"active":true},
    {"id":"D20.03","dir":"D20","name":"Инструменты и расходники","slug":"instrumenty-i-rashodniki","order":77,"active":true},
    {"id":"D21.01","dir":"D21","name":"Проктологический кабинет","slug":"proktologicheskiy-kabinet","order":78,"active":true},
    {"id":"D21.02","dir":"D21","name":"Проктологические инструменты","slug":"proktologicheskie-instrumenty","order":79,"active":true},
    {"id":"D21.03","dir":"D21","name":"Расходные материалы","slug":"rashodnye-materialy","order":80,"active":true},
    {"id":"D22.01","dir":"D22","name":"Урологическая диагностика","slug":"urologicheskaya-diagnostika","order":81,"active":true},
    {"id":"D22.02","dir":"D22","name":"Урологические инструменты","slug":"urologicheskie-instrumenty","order":82,"active":true},
    {"id":"D22.03","dir":"D22","name":"Катетеры и расходные материалы","slug":"katetery-i-rashodnye-materialy","order":83,"active":true},
    {"id":"D23.01","dir":"D23","name":"Кардиологическая диагностика","slug":"kardiologicheskaya-diagnostika","order":84,"active":true},
    {"id":"D23.02","dir":"D23","name":"Кардиологический мониторинг","slug":"kardiologicheskiy-monitoring","order":85,"active":true},
    {"id":"D23.03","dir":"D23","name":"Расходные материалы для кардиологии","slug":"rashodnye-materialy-dlya-kardiologii","order":86,"active":true}
  ],
  groups: [
    {"id":"G0001","name":"Гинекологические кресла","slug":"ginekologicheskie-kresla","cat":"C02","sub":"S018","priority":"B","order":1,"active":true},
    {"id":"G0002","name":"Кольпоскопы","slug":"kolposkopy","cat":"C01","sub":"S001","priority":"B","order":2,"active":true},
    {"id":"G0003","name":"Гинекологические инструменты","slug":"ginekologicheskie-instrumenty","cat":"C03","sub":"S027","priority":"B","order":3,"active":true},
    {"id":"G0004","name":"Смотровые светильники","slug":"smotrovye-svetilniki","cat":"C01","sub":"S005","priority":"B","order":4,"active":true},
    {"id":"G0005","name":"Кушетки и смотровые столы","slug":"kushetki-i-smotrovye-stoly","cat":"C02","sub":"S017","priority":"B","order":5,"active":true},
    {"id":"G0006","name":"Фетальные мониторы","slug":"fetalnye-monitory","cat":"C01","sub":"S001","priority":"B","order":6,"active":true},
    {"id":"G0007","name":"Фетальные допплеры","slug":"fetalnye-dopplery","cat":"C01","sub":"S001","priority":"B","order":7,"active":true},
    {"id":"G0008","name":"Акушерские кровати и столы","slug":"akusherskie-krovati-i-stoly","cat":"C02","sub":"S016","priority":"B","order":8,"active":true},
    {"id":"G0009","name":"Аспираторы","slug":"aspiratory","cat":"C01","sub":"S003","priority":"B","order":9,"active":true},
    {"id":"G0010","name":"УЗИ-аппараты","slug":"uzi-apparaty","cat":"C01","sub":"S001","priority":"B","order":10,"active":true},
    {"id":"G0011","name":"Датчики для УЗИ","slug":"datchiki-dlya-uzi","cat":"C01","sub":"S001","priority":"B","order":11,"active":true},
    {"id":"G0012","name":"Гель и бумага для УЗИ","slug":"gel-i-bumaga-dlya-uzi","cat":"C04","sub":"S042","priority":"B","order":12,"active":true},
    {"id":"G0013","name":"Одноразовые гинекологические наборы","slug":"odnorazovye-ginekologicheskie-nabory","cat":"C04","sub":"","priority":"B","order":13,"active":true},
    {"id":"G0014","name":"Цитологические щётки и шпатели","slug":"citologicheskie-schetki-i-shpateli","cat":"C04","sub":"","priority":"B","order":14,"active":true},
    {"id":"G0015","name":"Одноразовые зеркала","slug":"odnorazovye-zerkala","cat":"C04","sub":"","priority":"B","order":15,"active":true},
    {"id":"G0016","name":"Пелёнки и простыни","slug":"pelenki-i-prostyni","cat":"C04","sub":"S047","priority":"B","order":16,"active":true},
    {"id":"G0017","name":"Аппараты ИВЛ","slug":"apparaty-ivl","cat":"C01","sub":"S003","priority":"A","order":17,"active":true},
    {"id":"G0018","name":"Наркозные аппараты","slug":"narkoznye-apparaty","cat":"C01","sub":"S004","priority":"A","order":18,"active":true},
    {"id":"G0019","name":"Кислородные концентраторы","slug":"kislorodnye-koncentratory","cat":"C01","sub":"S003","priority":"A","order":19,"active":true},
    {"id":"G0020","name":"Кислородные системы","slug":"kislorodnye-sistemy","cat":"C01","sub":"S003","priority":"A","order":20,"active":true},
    {"id":"G0021","name":"Мониторы пациента","slug":"monitory-pacienta","cat":"C01","sub":"S003","priority":"A","order":21,"active":true},
    {"id":"G0022","name":"Капнографы","slug":"kapnografy","cat":"C01","sub":"S004","priority":"A","order":22,"active":true},
    {"id":"G0023","name":"Пульсоксиметры","slug":"pulsoksimetry","cat":"C01","sub":"S001","priority":"A","order":23,"active":true},
    {"id":"G0024","name":"Дефибрилляторы","slug":"defibrillyatory","cat":"C01","sub":"S003","priority":"A","order":24,"active":true},
    {"id":"G0025","name":"Инфузионные насосы","slug":"infuzionnye-nasosy","cat":"C01","sub":"S003","priority":"A","order":25,"active":true},
    {"id":"G0026","name":"Шприцевые насосы","slug":"shpricevye-nasosy","cat":"C01","sub":"S003","priority":"A","order":26,"active":true},
    {"id":"G0027","name":"Инфузионные стойки","slug":"infuzionnye-stoyki","cat":"C02","sub":"S023","priority":"A","order":27,"active":true},
    {"id":"G0028","name":"Инфузионные расходные материалы","slug":"infuzionnye-rashodnye-materialy","cat":"C04","sub":"S037","priority":"A","order":28,"active":true},
    {"id":"G0029","name":"Дыхательные контуры","slug":"dyhatelnye-kontury","cat":"C04","sub":"S043","priority":"A","order":29,"active":true},
    {"id":"G0030","name":"Дыхательные фильтры","slug":"dyhatelnye-filtry","cat":"C04","sub":"S043","priority":"A","order":30,"active":true},
    {"id":"G0031","name":"Эндотрахеальные трубки","slug":"endotrahealnye-trubki","cat":"C04","sub":"S043","priority":"A","order":31,"active":true},
    {"id":"G0032","name":"Ларингеальные маски","slug":"laringealnye-maski","cat":"C04","sub":"S043","priority":"A","order":32,"active":true},
    {"id":"G0033","name":"Кислородные маски и канюли","slug":"kislorodnye-maski-i-kanyuli","cat":"C04","sub":"S043","priority":"A","order":33,"active":true},
    {"id":"G0034","name":"Реанимационные кровати","slug":"reanimacionnye-krovati","cat":"C02","sub":"S016","priority":"A","order":34,"active":true},
    {"id":"G0035","name":"Тележки реанимационные","slug":"telezhki-reanimacionnye","cat":"C02","sub":"S020","priority":"A","order":35,"active":true},
    {"id":"G0036","name":"Прикроватные тумбы и стойки","slug":"prikrovatnye-tumby-i-stoyki","cat":"C02","sub":"S022","priority":"A","order":36,"active":true},
    {"id":"G0037","name":"УЗИ-датчики","slug":"uzi-datchiki","cat":"C01","sub":"S001","priority":"A","order":37,"active":true},
    {"id":"G0038","name":"Принтеры и расходники для УЗИ","slug":"printery-i-rashodniki-dlya-uzi","cat":"C04","sub":"S042","priority":"A","order":38,"active":true},
    {"id":"G0039","name":"Тонометры","slug":"tonometry","cat":"C01","sub":"S001","priority":"A","order":39,"active":true},
    {"id":"G0040","name":"Термометры","slug":"termometry","cat":"C01","sub":"S001","priority":"A","order":40,"active":true},
    {"id":"G0041","name":"Стетоскопы и фонендоскопы","slug":"stetoskopy-i-fonendoskopy","cat":"C03","sub":"S032","priority":"A","order":41,"active":true},
    {"id":"G0042","name":"Отоскопы","slug":"otoskopy","cat":"C01","sub":"S001","priority":"A","order":42,"active":true},
    {"id":"G0043","name":"Офтальмоскопы","slug":"oftalmoskopy","cat":"C01","sub":"S010","priority":"A","order":43,"active":true},
    {"id":"G0044","name":"Дерматоскопы","slug":"dermatoskopy","cat":"C01","sub":"S001","priority":"A","order":44,"active":true},
    {"id":"G0045","name":"Электроды ЭКГ","slug":"elektrody-ekg","cat":"C04","sub":"S042","priority":"A","order":45,"active":true},
    {"id":"G0046","name":"Бумага ЭКГ и термобумага","slug":"bumaga-ekg-i-termobumaga","cat":"C04","sub":"S042","priority":"A","order":46,"active":true},
    {"id":"G0047","name":"Гель для УЗИ","slug":"gel-dlya-uzi","cat":"C04","sub":"S042","priority":"A","order":47,"active":true},
    {"id":"G0048","name":"Электрокардиографы","slug":"elektrokardiografy","cat":"C01","sub":"S002","priority":"A","order":48,"active":true},
    {"id":"G0049","name":"Компьютерные ЭКГ-системы","slug":"kompyuternye-ekg-sistemy","cat":"C01","sub":"S002","priority":"A","order":49,"active":true},
    {"id":"G0050","name":"Электроды и бумага ЭКГ","slug":"elektrody-i-bumaga-ekg","cat":"C04","sub":"S042","priority":"A","order":50,"active":true},
    {"id":"G0051","name":"Холтеры ЭКГ","slug":"holtery-ekg","cat":"C01","sub":"S002","priority":"A","order":51,"active":true},
    {"id":"G0052","name":"Суточные мониторы АД","slug":"sutochnye-monitory-ad","cat":"C01","sub":"S002","priority":"A","order":52,"active":true},
    {"id":"G0053","name":"Кардиорегистраторы","slug":"kardioregistratory","cat":"C01","sub":"S002","priority":"A","order":53,"active":true},
    {"id":"G0054","name":"Спирометры","slug":"spirometry","cat":"C01","sub":"S002","priority":"A","order":54,"active":true},
    {"id":"G0055","name":"Мундштуки и фильтры","slug":"mundshtuki-i-filtry","cat":"C04","sub":"S042","priority":"A","order":55,"active":true},
    {"id":"G0056","name":"Электроэнцефалографы","slug":"elektroencefalografy","cat":"C01","sub":"S002","priority":"A","order":56,"active":true},
    {"id":"G0057","name":"Электроды и аксессуары ЭЭГ","slug":"elektrody-i-aksessuary-eeg","cat":"C04","sub":"S042","priority":"A","order":57,"active":true},
    {"id":"G0058","name":"Стресс-тест системы","slug":"stress-test-sistemy","cat":"C01","sub":"S002","priority":"A","order":58,"active":true},
    {"id":"G0059","name":"Мониторинг при нагрузке","slug":"monitoring-pri-nagruzke","cat":"C01","sub":"S002","priority":"A","order":59,"active":true},
    {"id":"G0060","name":"Гематологические анализаторы","slug":"gematologicheskie-analizatory","cat":"C01","sub":"S006","priority":"A","order":60,"active":true},
    {"id":"G0061","name":"Биохимические анализаторы","slug":"biohimicheskie-analizatory","cat":"C01","sub":"S006","priority":"A","order":61,"active":true},
    {"id":"G0062","name":"Анализаторы мочи","slug":"analizatory-mochi","cat":"C01","sub":"S006","priority":"A","order":62,"active":true},
    {"id":"G0063","name":"Коагулометры","slug":"koagulometry","cat":"C01","sub":"S006","priority":"A","order":63,"active":true},
    {"id":"G0064","name":"Центрифуги","slug":"centrifugi","cat":"C01","sub":"S006","priority":"A","order":64,"active":true},
    {"id":"G0065","name":"Микроскопы","slug":"mikroskopy","cat":"C01","sub":"S006","priority":"A","order":65,"active":true},
    {"id":"G0066","name":"Термостаты и инкубаторы","slug":"termostaty-i-inkubatory","cat":"C01","sub":"S006","priority":"A","order":66,"active":true},
    {"id":"G0067","name":"Лабораторные весы","slug":"laboratornye-vesy","cat":"C01","sub":"S006","priority":"A","order":67,"active":true},
    {"id":"G0068","name":"Дистилляторы","slug":"distillyatory","cat":"C01","sub":"S006","priority":"A","order":68,"active":true},
    {"id":"G0069","name":"Лабораторные холодильники","slug":"laboratornye-holodilniki","cat":"C01","sub":"S006","priority":"A","order":69,"active":true},
    {"id":"G0070","name":"Морозильники","slug":"morozilniki","cat":"C01","sub":"S006","priority":"A","order":70,"active":true},
    {"id":"G0071","name":"Термоконтейнеры","slug":"termokonteynery","cat":"C04","sub":"S041","priority":"A","order":71,"active":true},
    {"id":"G0072","name":"Лабораторные столы","slug":"laboratornye-stoly","cat":"C02","sub":"S024","priority":"A","order":72,"active":true},
    {"id":"G0073","name":"Вытяжные шкафы","slug":"vytyazhnye-shkafy","cat":"C02","sub":"S024","priority":"A","order":73,"active":true},
    {"id":"G0074","name":"Шкафы и тумбы лабораторные","slug":"shkafy-i-tumby-laboratornye","cat":"C02","sub":"S024","priority":"A","order":74,"active":true},
    {"id":"G0075","name":"Пробирки и контейнеры","slug":"probirki-i-konteynery","cat":"C04","sub":"S041","priority":"A","order":75,"active":true},
    {"id":"G0076","name":"Наконечники и дозаторы","slug":"nakonechniki-i-dozatory","cat":"C04","sub":"S041","priority":"A","order":76,"active":true},
    {"id":"G0077","name":"Стёкла и чашки Петри","slug":"stekla-i-chashki-petri","cat":"C04","sub":"S041","priority":"A","order":77,"active":true},
    {"id":"G0078","name":"Автоклавы","slug":"avtoklavy","cat":"C01","sub":"S007","priority":"A","order":78,"active":true},
    {"id":"G0079","name":"Сухожаровые шкафы","slug":"suhozharovye-shkafy","cat":"C01","sub":"S007","priority":"A","order":79,"active":true},
    {"id":"G0080","name":"Плазменные стерилизаторы","slug":"plazmennye-sterilizatory","cat":"C01","sub":"S007","priority":"A","order":80,"active":true},
    {"id":"G0081","name":"Ультразвуковые мойки","slug":"ultrazvukovye-moyki","cat":"C01","sub":"S007","priority":"A","order":81,"active":true},
    {"id":"G0082","name":"Моечно-дезинфекционные машины","slug":"moechno-dezinfekcionnye-mashiny","cat":"C01","sub":"S007","priority":"A","order":82,"active":true},
    {"id":"G0083","name":"Запаиватели пакетов","slug":"zapaivateli-paketov","cat":"C01","sub":"S007","priority":"A","order":83,"active":true},
    {"id":"G0084","name":"Рециркуляторы","slug":"recirkulyatory","cat":"C01","sub":"S007","priority":"A","order":84,"active":true},
    {"id":"G0085","name":"Бактерицидные облучатели","slug":"baktericidnye-obluchateli","cat":"C01","sub":"S007","priority":"A","order":85,"active":true},
    {"id":"G0086","name":"Дезинфекционные камеры","slug":"dezinfekcionnye-kamery","cat":"C01","sub":"S007","priority":"A","order":86,"active":true},
    {"id":"G0087","name":"Пакеты и рулоны для стерилизации","slug":"pakety-i-rulony-dlya-sterilizacii","cat":"C04","sub":"S040","priority":"A","order":87,"active":true},
    {"id":"G0088","name":"Индикаторы стерилизации","slug":"indikatory-sterilizacii","cat":"C04","sub":"S040","priority":"A","order":88,"active":true},
    {"id":"G0089","name":"Крафт-пакеты","slug":"kraft-pakety","cat":"C04","sub":"S040","priority":"A","order":89,"active":true},
    {"id":"G0090","name":"Стоматологические установки","slug":"stomatologicheskie-ustanovki","cat":"C01","sub":"S008","priority":"A","order":90,"active":true},
    {"id":"G0091","name":"Компрессоры","slug":"kompressory","cat":"C01","sub":"S008","priority":"A","order":91,"active":true},
    {"id":"G0092","name":"Аспирационные системы","slug":"aspiracionnye-sistemy","cat":"C01","sub":"S008","priority":"A","order":92,"active":true},
    {"id":"G0093","name":"Стоматологические кресла","slug":"stomatologicheskie-kresla","cat":"C02","sub":"S018","priority":"A","order":93,"active":true},
    {"id":"G0094","name":"Стоматологический рентген","slug":"stomatologicheskiy-rentgen","cat":"C01","sub":"S013","priority":"A","order":94,"active":true},
    {"id":"G0095","name":"Визиографы","slug":"viziografy","cat":"C01","sub":"S013","priority":"A","order":95,"active":true},
    {"id":"G0096","name":"Интраоральные камеры","slug":"intraoralnye-kamery","cat":"C01","sub":"S008","priority":"A","order":96,"active":true},
    {"id":"G0097","name":"Автоклавы для стоматологии","slug":"avtoklavy-dlya-stomatologii","cat":"C01","sub":"S007","priority":"A","order":97,"active":true},
    {"id":"G0098","name":"Запаиватели и расходники","slug":"zapaivateli-i-rashodniki","cat":"C04","sub":"S040","priority":"A","order":98,"active":true},
    {"id":"G0099","name":"Инструменты для осмотра","slug":"instrumenty-dlya-osmotra","cat":"C03","sub":"S028","priority":"A","order":99,"active":true},
    {"id":"G0100","name":"Инструменты для удаления","slug":"instrumenty-dlya-udaleniya","cat":"C03","sub":"S028","priority":"A","order":100,"active":true},
    {"id":"G0101","name":"Эндодонтические инструменты","slug":"endodonticheskie-instrumenty","cat":"C03","sub":"S028","priority":"A","order":101,"active":true},
    {"id":"G0102","name":"Пломбировочные материалы","slug":"plombirovochnye-materialy","cat":"C04","sub":"S045","priority":"A","order":102,"active":true},
    {"id":"G0103","name":"Слюноотсосы и наконечники","slug":"slyunootsosy-i-nakonechniki","cat":"C04","sub":"S045","priority":"A","order":103,"active":true},
    {"id":"G0104","name":"Валики, салфетки и чехлы","slug":"valiki-salfetki-i-chehly","cat":"C04","sub":"S045","priority":"A","order":104,"active":true},
    {"id":"G0105","name":"Операционные светильники","slug":"operacionnye-svetilniki","cat":"C01","sub":"S005","priority":"A","order":105,"active":true},
    {"id":"G0106","name":"Операционные столы","slug":"operacionnye-stoly","cat":"C02","sub":"S019","priority":"A","order":106,"active":true},
    {"id":"G0107","name":"Электрохирургические коагуляторы","slug":"elektrohirurgicheskie-koagulyatory","cat":"C01","sub":"S005","priority":"A","order":107,"active":true},
    {"id":"G0108","name":"Эвакуаторы дыма","slug":"evakuatory-dyma","cat":"C01","sub":"S005","priority":"A","order":108,"active":true},
    {"id":"G0109","name":"Отсасыватели хирургические","slug":"otsasyvateli-hirurgicheskie","cat":"C01","sub":"S005","priority":"A","order":109,"active":true},
    {"id":"G0110","name":"Перевязочные столы и тележки","slug":"perevyazochnye-stoly-i-telezhki","cat":"C02","sub":"S019","priority":"A","order":110,"active":true},
    {"id":"G0111","name":"Светильники смотровые","slug":"svetilniki-smotrovye","cat":"C01","sub":"S005","priority":"A","order":111,"active":true},
    {"id":"G0112","name":"Наборы хирургических инструментов","slug":"nabory-hirurgicheskih-instrumentov","cat":"C03","sub":"S026","priority":"A","order":112,"active":true},
    {"id":"G0113","name":"Зажимы, пинцеты, ножницы","slug":"zazhimy-pincety-nozhnicy","cat":"C03","sub":"S026","priority":"A","order":113,"active":true},
    {"id":"G0114","name":"Иглодержатели и скальпели","slug":"igloderzhateli-i-skalpeli","cat":"C03","sub":"S026","priority":"A","order":114,"active":true},
    {"id":"G0115","name":"Шовный материал","slug":"shovnyy-material","cat":"C04","sub":"S044","priority":"A","order":115,"active":true},
    {"id":"G0116","name":"Операционное бельё","slug":"operacionnoe-bele","cat":"C04","sub":"S044","priority":"A","order":116,"active":true},
    {"id":"G0117","name":"Дренажи и аспирационные трубки","slug":"drenazhi-i-aspiracionnye-trubki","cat":"C04","sub":"S044","priority":"A","order":117,"active":true},
    {"id":"G0118","name":"Видеоэндоскопические стойки","slug":"videoendoskopicheskie-stoyki","cat":"C01","sub":"S014","priority":"C","order":118,"active":false},
    {"id":"G0119","name":"Источники света и камеры","slug":"istochniki-sveta-i-kamery","cat":"C01","sub":"S014","priority":"C","order":119,"active":false},
    {"id":"G0120","name":"Инсуффляторы","slug":"insufflyatory","cat":"C01","sub":"S014","priority":"C","order":120,"active":false},
    {"id":"G0121","name":"Гастроскопы","slug":"gastroskopy","cat":"C01","sub":"S014","priority":"C","order":121,"active":false},
    {"id":"G0122","name":"Колоноскопы","slug":"kolonoskopy","cat":"C01","sub":"S014","priority":"C","order":122,"active":false},
    {"id":"G0123","name":"Бронхоскопы","slug":"bronhoskopy","cat":"C01","sub":"S014","priority":"C","order":123,"active":false},
    {"id":"G0124","name":"Мойки для эндоскопов","slug":"moyki-dlya-endoskopov","cat":"C01","sub":"S007","priority":"C","order":124,"active":false},
    {"id":"G0125","name":"Шкафы хранения эндоскопов","slug":"shkafy-hraneniya-endoskopov","cat":"C02","sub":"S021","priority":"C","order":125,"active":false},
    {"id":"G0126","name":"Расходники для обработки","slug":"rashodniki-dlya-obrabotki","cat":"C04","sub":"S039","priority":"C","order":126,"active":false},
    {"id":"G0127","name":"Биопсийные щипцы","slug":"biopsiynye-schipcy","cat":"C03","sub":"S026","priority":"C","order":127,"active":false},
    {"id":"G0128","name":"Петли и катетеры","slug":"petli-i-katetery","cat":"C04","sub":"S044","priority":"C","order":128,"active":false},
    {"id":"G0129","name":"Инкубаторы для новорождённых","slug":"inkubatory-dlya-novorozhdennyh","cat":"C01","sub":"S009","priority":"B","order":129,"active":true},
    {"id":"G0130","name":"Открытые реанимационные системы","slug":"otkrytye-reanimacionnye-sistemy","cat":"C01","sub":"S009","priority":"B","order":130,"active":true},
    {"id":"G0131","name":"Неонатальные ИВЛ","slug":"neonatalnye-ivl","cat":"C01","sub":"S009","priority":"B","order":131,"active":true},
    {"id":"G0132","name":"Мониторы новорождённых","slug":"monitory-novorozhdennyh","cat":"C01","sub":"S003","priority":"B","order":132,"active":true},
    {"id":"G0133","name":"Фототерапевтические лампы","slug":"fototerapevticheskie-lampy","cat":"C01","sub":"S009","priority":"B","order":133,"active":true},
    {"id":"G0134","name":"Обогреватели новорождённых","slug":"obogrevateli-novorozhdennyh","cat":"C01","sub":"S009","priority":"B","order":134,"active":true},
    {"id":"G0135","name":"Весы для новорождённых","slug":"vesy-dlya-novorozhdennyh","cat":"C01","sub":"S001","priority":"B","order":135,"active":true},
    {"id":"G0136","name":"Кроватки для новорождённых","slug":"krovatki-dlya-novorozhdennyh","cat":"C02","sub":"S016","priority":"B","order":136,"active":true},
    {"id":"G0137","name":"Пеленальные столы","slug":"pelenalnye-stoly","cat":"C02","sub":"S019","priority":"B","order":137,"active":true},
    {"id":"G0138","name":"Тележки и тумбы","slug":"telezhki-i-tumby","cat":"C02","sub":"","priority":"B","order":138,"active":true},
    {"id":"G0139","name":"Неонатальные датчики","slug":"neonatalnye-datchiki","cat":"C04","sub":"S043","priority":"B","order":139,"active":true},
    {"id":"G0140","name":"Маски и контуры","slug":"maski-i-kontury","cat":"C04","sub":"S043","priority":"B","order":140,"active":true},
    {"id":"G0141","name":"Пелёнки и уход","slug":"pelenki-i-uhod","cat":"C04","sub":"S047","priority":"B","order":141,"active":true},
    {"id":"G0142","name":"ЛОР-комбайны","slug":"lor-kombayny","cat":"C01","sub":"S011","priority":"B","order":142,"active":true},
    {"id":"G0143","name":"ЛОР-кресла","slug":"lor-kresla","cat":"C02","sub":"S018","priority":"B","order":143,"active":true},
    {"id":"G0144","name":"Налобные осветители","slug":"nalobnye-osvetiteli","cat":"C01","sub":"S011","priority":"B","order":144,"active":true},
    {"id":"G0145","name":"ЛОР-аспираторы","slug":"lor-aspiratory","cat":"C01","sub":"S011","priority":"B","order":145,"active":true},
    {"id":"G0146","name":"Аудиометры","slug":"audiometry","cat":"C01","sub":"S011","priority":"B","order":146,"active":true},
    {"id":"G0147","name":"Тимпанометры","slug":"timpanometry","cat":"C01","sub":"S011","priority":"B","order":147,"active":true},
    {"id":"G0148","name":"Расходники для аудиологии","slug":"rashodniki-dlya-audiologii","cat":"C04","sub":"S042","priority":"B","order":148,"active":true},
    {"id":"G0149","name":"ЛОР-эндоскопы","slug":"lor-endoskopy","cat":"C01","sub":"S011","priority":"B","order":149,"active":true},
    {"id":"G0150","name":"Камеры и источники света","slug":"kamery-i-istochniki-sveta","cat":"C01","sub":"S014","priority":"B","order":150,"active":true},
    {"id":"G0151","name":"Носовые зеркала","slug":"nosovye-zerkala","cat":"C03","sub":"S029","priority":"B","order":151,"active":true},
    {"id":"G0152","name":"Ушные воронки и зонды","slug":"ushnye-voronki-i-zondy","cat":"C03","sub":"S029","priority":"B","order":152,"active":true},
    {"id":"G0153","name":"ЛОР-наборы","slug":"lor-nabory","cat":"C03","sub":"S034","priority":"B","order":153,"active":true},
    {"id":"G0154","name":"Щелевые лампы","slug":"schelevye-lampy","cat":"C01","sub":"S010","priority":"B","order":154,"active":true},
    {"id":"G0155","name":"Авторефрактометры","slug":"avtorefraktometry","cat":"C01","sub":"S010","priority":"B","order":155,"active":true},
    {"id":"G0156","name":"Периметры","slug":"perimetry","cat":"C01","sub":"S010","priority":"B","order":156,"active":true},
    {"id":"G0157","name":"Офтальмологические кресла","slug":"oftalmologicheskie-kresla","cat":"C02","sub":"S018","priority":"B","order":157,"active":true},
    {"id":"G0158","name":"Офтальмологические столы","slug":"oftalmologicheskie-stoly","cat":"C02","sub":"S019","priority":"B","order":158,"active":true},
    {"id":"G0159","name":"Таблицы проверки зрения","slug":"tablicy-proverki-zreniya","cat":"C01","sub":"S010","priority":"B","order":159,"active":true},
    {"id":"G0160","name":"Пинцеты и ножницы","slug":"pincety-i-nozhnicy","cat":"C03","sub":"S030","priority":"B","order":160,"active":true},
    {"id":"G0161","name":"Векорасширители","slug":"vekorasshiriteli","cat":"C03","sub":"S030","priority":"B","order":161,"active":true},
    {"id":"G0162","name":"Офтальмологические наборы","slug":"oftalmologicheskie-nabory","cat":"C03","sub":"S034","priority":"B","order":162,"active":true},
    {"id":"G0163","name":"Одноразовые офтальмологические расходники","slug":"odnorazovye-oftalmologicheskie-rashodniki","cat":"C04","sub":"S042","priority":"B","order":163,"active":true},
    {"id":"G0164","name":"Дезинфекция и уход","slug":"dezinfekciya-i-uhod","cat":"C04","sub":"S039","priority":"B","order":164,"active":true},
    {"id":"G0165","name":"Рентген-аппараты","slug":"rentgen-apparaty","cat":"C01","sub":"S013","priority":"C","order":165,"active":false},
    {"id":"G0166","name":"С-дуги","slug":"s-dugi","cat":"C01","sub":"S013","priority":"C","order":166,"active":false},
    {"id":"G0167","name":"Маммографы","slug":"mammografy","cat":"C01","sub":"S013","priority":"C","order":167,"active":false},
    {"id":"G0168","name":"ОПТГ / КЛКТ","slug":"optg-klkt","cat":"C01","sub":"S013","priority":"C","order":168,"active":false},
    {"id":"G0169","name":"Средства рентгенозащиты","slug":"sredstva-rentgenozaschity","cat":"C02","sub":"","priority":"C","order":169,"active":false},
    {"id":"G0170","name":"Рентгеновская плёнка и расходники","slug":"rentgenovskaya-plenka-i-rashodniki","cat":"C04","sub":"S042","priority":"C","order":170,"active":false},
    {"id":"G0171","name":"Мебель для рентген-кабинета","slug":"mebel-dlya-rentgen-kabineta","cat":"C02","sub":"","priority":"C","order":171,"active":false},
    {"id":"G0172","name":"Электротерапия","slug":"elektroterapiya","cat":"C01","sub":"S012","priority":"B","order":172,"active":true},
    {"id":"G0173","name":"Магнитотерапия","slug":"magnitoterapiya","cat":"C01","sub":"S012","priority":"B","order":173,"active":true},
    {"id":"G0174","name":"Ультразвуковая терапия","slug":"ultrazvukovaya-terapiya","cat":"C01","sub":"S012","priority":"B","order":174,"active":true},
    {"id":"G0175","name":"Лазеротерапия","slug":"lazeroterapiya","cat":"C01","sub":"S012","priority":"B","order":175,"active":true},
    {"id":"G0176","name":"УВЧ и СВЧ терапия","slug":"uvch-i-svch-terapiya","cat":"C01","sub":"S012","priority":"B","order":176,"active":true},
    {"id":"G0177","name":"Реабилитационные тренажёры","slug":"reabilitacionnye-trenazhery","cat":"C01","sub":"S012","priority":"B","order":177,"active":true},
    {"id":"G0178","name":"Вертикализаторы","slug":"vertikalizatory","cat":"C01","sub":"S012","priority":"B","order":178,"active":true},
    {"id":"G0179","name":"Оборудование для ЛФК","slug":"oborudovanie-dlya-lfk","cat":"C01","sub":"S012","priority":"B","order":179,"active":true},
    {"id":"G0180","name":"Массажные кушетки","slug":"massazhnye-kushetki","cat":"C02","sub":"S017","priority":"B","order":180,"active":true},
    {"id":"G0181","name":"Массажное оборудование","slug":"massazhnoe-oborudovanie","cat":"C01","sub":"S012","priority":"B","order":181,"active":true},
    {"id":"G0182","name":"Электроды и накладки","slug":"elektrody-i-nakladki","cat":"C04","sub":"S042","priority":"B","order":182,"active":true},
    {"id":"G0183","name":"Гели и контактные средства","slug":"geli-i-kontaktnye-sredstva","cat":"C04","sub":"S039","priority":"B","order":183,"active":true},
    {"id":"G0184","name":"Ортопедические инструменты","slug":"ortopedicheskie-instrumenty","cat":"C03","sub":"S031","priority":"C","order":184,"active":true},
    {"id":"G0185","name":"Операционные аксессуары","slug":"operacionnye-aksessuary","cat":"C01","sub":"S005","priority":"C","order":185,"active":true},
    {"id":"G0186","name":"Шины","slug":"shiny","cat":"C04","sub":"","priority":"C","order":186,"active":true},
    {"id":"G0187","name":"Воротники","slug":"vorotniki","cat":"C04","sub":"S047","priority":"C","order":187,"active":true},
    {"id":"G0188","name":"Ортезы и фиксаторы","slug":"ortezy-i-fiksatory","cat":"C04","sub":"S047","priority":"C","order":188,"active":true},
    {"id":"G0189","name":"Средства передвижения","slug":"sredstva-peredvizheniya","cat":"C02","sub":"","priority":"C","order":189,"active":true},
    {"id":"G0190","name":"Физиотерапевтические аппараты","slug":"fizioterapevticheskie-apparaty","cat":"C01","sub":"S012","priority":"C","order":190,"active":true},
    {"id":"G0191","name":"Портативные ИВЛ","slug":"portativnye-ivl","cat":"C01","sub":"S015","priority":"B","order":191,"active":true},
    {"id":"G0192","name":"Портативные мониторы пациента","slug":"portativnye-monitory-pacienta","cat":"C01","sub":"S003","priority":"B","order":192,"active":true},
    {"id":"G0193","name":"Портативные аспираторы","slug":"portativnye-aspiratory","cat":"C01","sub":"S015","priority":"B","order":193,"active":true},
    {"id":"G0194","name":"Носилки","slug":"nosilki","cat":"C02","sub":"S015","priority":"B","order":194,"active":true},
    {"id":"G0195","name":"Шины и воротники","slug":"shiny-i-vorotniki","cat":"C04","sub":"S015","priority":"B","order":195,"active":true},
    {"id":"G0196","name":"Кресла-каталки","slug":"kresla-katalki","cat":"C02","sub":"S018","priority":"B","order":196,"active":true},
    {"id":"G0197","name":"Кислородные баллоны и системы","slug":"kislorodnye-ballony-i-sistemy","cat":"C01","sub":"S015","priority":"B","order":197,"active":true},
    {"id":"G0198","name":"Мешки Амбу","slug":"meshki-ambu","cat":"C04","sub":"S043","priority":"B","order":198,"active":true},
    {"id":"G0199","name":"Маски и канюли","slug":"maski-i-kanyuli","cat":"C04","sub":"S043","priority":"B","order":199,"active":true},
    {"id":"G0200","name":"Реанимационные укладки","slug":"reanimacionnye-ukladki","cat":"C01","sub":"","priority":"B","order":200,"active":true},
    {"id":"G0201","name":"Перевязочные материалы","slug":"perevyazochnye-materialy","cat":"C04","sub":"S038","priority":"B","order":201,"active":true},
    {"id":"G0202","name":"Инъекционные материалы","slug":"inekcionnye-materialy","cat":"C04","sub":"S037","priority":"B","order":202,"active":true},
    {"id":"G0203","name":"Кресла донорские","slug":"kresla-donorskie","cat":"C02","sub":"S018","priority":"C","order":203,"active":false},
    {"id":"G0204","name":"Весы-помешиватели крови","slug":"vesy-pomeshivateli-krovi","cat":"C01","sub":"S006","priority":"C","order":204,"active":false},
    {"id":"G0205","name":"Системы и контейнеры для крови","slug":"sistemy-i-konteynery-dlya-krovi","cat":"C04","sub":"S041","priority":"C","order":205,"active":false},
    {"id":"G0206","name":"Холодильники для крови","slug":"holodilniki-dlya-krovi","cat":"C01","sub":"S006","priority":"C","order":206,"active":false},
    {"id":"G0207","name":"Морозильники плазмы","slug":"morozilniki-plazmy","cat":"C01","sub":"S006","priority":"C","order":207,"active":false},
    {"id":"G0208","name":"Центрифуги для крови","slug":"centrifugi-dlya-krovi","cat":"C01","sub":"S006","priority":"C","order":208,"active":false},
    {"id":"G0209","name":"Запаиватели трубок","slug":"zapaivateli-trubok","cat":"C01","sub":"S006","priority":"C","order":209,"active":false},
    {"id":"G0210","name":"Лабораторные расходники","slug":"laboratornye-rashodniki","cat":"C04","sub":"S041","priority":"C","order":210,"active":false},
    {"id":"G0211","name":"Кислородные станции","slug":"kislorodnye-stancii","cat":"C01","sub":"S003","priority":"B","order":211,"active":true},
    {"id":"G0212","name":"Кислородные баллоны и редукторы","slug":"kislorodnye-ballony-i-reduktory","cat":"C01","sub":"S003","priority":"B","order":212,"active":true},
    {"id":"G0213","name":"Кислородные маски","slug":"kislorodnye-maski","cat":"C04","sub":"S043","priority":"B","order":213,"active":true},
    {"id":"G0214","name":"Назальные канюли","slug":"nazalnye-kanyuli","cat":"C04","sub":"S043","priority":"B","order":214,"active":true},
    {"id":"G0215","name":"Увлажнители и аксессуары","slug":"uvlazhniteli-i-aksessuary","cat":"C04","sub":"S043","priority":"B","order":215,"active":true},
    {"id":"G0216","name":"CPAP/BiPAP аппараты","slug":"cpap-bipap-apparaty","cat":"C01","sub":"S003","priority":"B","order":216,"active":true},
    {"id":"G0217","name":"Маски для НИВЛ","slug":"maski-dlya-nivl","cat":"C04","sub":"S043","priority":"B","order":217,"active":true},
    {"id":"G0218","name":"Шины транспортные","slug":"shiny-transportnye","cat":"C04","sub":"S015","priority":"C","order":218,"active":true},
    {"id":"G0219","name":"Воротники шейные","slug":"vorotniki-sheynye","cat":"C04","sub":"S047","priority":"C","order":219,"active":true},
    {"id":"G0220","name":"Носилки и щиты","slug":"nosilki-i-schity","cat":"C02","sub":"S015","priority":"C","order":220,"active":true},
    {"id":"G0221","name":"Ортезы","slug":"ortezy","cat":"C04","sub":"S047","priority":"C","order":221,"active":true},
    {"id":"G0222","name":"Бандажи и фиксаторы","slug":"bandazhi-i-fiksatory","cat":"C04","sub":"S047","priority":"C","order":222,"active":true},
    {"id":"G0223","name":"Гипсовые и полимерные материалы","slug":"gipsovye-i-polimernye-materialy","cat":"C04","sub":"S044","priority":"C","order":223,"active":true},
    {"id":"G0224","name":"Лампы Вуда","slug":"lampy-vuda","cat":"C01","sub":"S001","priority":"C","order":224,"active":false},
    {"id":"G0225","name":"Фотофиксация и ПО","slug":"fotofiksaciya-i-po","cat":"C01","sub":"S001","priority":"C","order":225,"active":false},
    {"id":"G0226","name":"Аппараты косметологии","slug":"apparaty-kosmetologii","cat":"C01","sub":"","priority":"C","order":226,"active":false},
    {"id":"G0227","name":"Лазерные системы","slug":"lazernye-sistemy","cat":"C01","sub":"","priority":"C","order":227,"active":false},
    {"id":"G0228","name":"Косметологические кресла","slug":"kosmetologicheskie-kresla","cat":"C02","sub":"S018","priority":"C","order":228,"active":false},
    {"id":"G0229","name":"Дерматологические инструменты","slug":"dermatologicheskie-instrumenty","cat":"C03","sub":"S032","priority":"C","order":229,"active":false},
    {"id":"G0230","name":"Одноразовые материалы","slug":"odnorazovye-materialy","cat":"C04","sub":"S036","priority":"C","order":230,"active":false},
    {"id":"G0231","name":"Дезинфекция и антисептика","slug":"dezinfekciya-i-antiseptika","cat":"C04","sub":"S039","priority":"C","order":231,"active":false},
    {"id":"G0232","name":"Проктологические кресла и столы","slug":"proktologicheskie-kresla-i-stoly","cat":"C02","sub":"S018","priority":"C","order":232,"active":false},
    {"id":"G0233","name":"Аноскопы и ректоскопы","slug":"anoskopy-i-rektoskopy","cat":"C01","sub":"S014","priority":"C","order":233,"active":false},
    {"id":"G0234","name":"Наборы инструментов","slug":"nabory-instrumentov","cat":"C03","sub":"S034","priority":"C","order":234,"active":false},
    {"id":"G0235","name":"Одноразовые наборы","slug":"odnorazovye-nabory","cat":"C04","sub":"S044","priority":"C","order":235,"active":false},
    {"id":"G0236","name":"Пелёнки и покрытия","slug":"pelenki-i-pokrytiya","cat":"C04","sub":"S047","priority":"C","order":236,"active":false},
    {"id":"G0237","name":"Уродинамические системы","slug":"urodinamicheskie-sistemy","cat":"C01","sub":"S001","priority":"C","order":237,"active":false},
    {"id":"G0238","name":"УЗИ для урологии","slug":"uzi-dlya-urologii","cat":"C01","sub":"S001","priority":"C","order":238,"active":false},
    {"id":"G0239","name":"Цистоскопы","slug":"cistoskopy","cat":"C01","sub":"S014","priority":"C","order":239,"active":false},
    {"id":"G0240","name":"Урологические инструменты","slug":"urologicheskie-instrumenty","cat":"C03","sub":"S026","priority":"C","order":240,"active":false},
    {"id":"G0241","name":"Урологические катетеры","slug":"urologicheskie-katetery","cat":"C04","sub":"","priority":"C","order":241,"active":false},
    {"id":"G0242","name":"Мочеприёмники","slug":"mochepriemniki","cat":"C04","sub":"S047","priority":"C","order":242,"active":false},
    {"id":"G0243","name":"Контейнеры и расходники","slug":"konteynery-i-rashodniki","cat":"C04","sub":"S041","priority":"C","order":243,"active":false},
    {"id":"G0244","name":"СМАД","slug":"smad","cat":"C01","sub":"S002","priority":"C","order":244,"active":true},
    {"id":"G0245","name":"Бумага ЭКГ","slug":"bumaga-ekg","cat":"C04","sub":"S042","priority":"C","order":245,"active":true},
    {"id":"G0246","name":"Манжеты и кабели","slug":"manzhety-i-kabeli","cat":"C04","sub":"S042","priority":"C","order":246,"active":true}
  ],
  links: [
    {"group":"G0001","section":"D01.01"},
    {"group":"G0002","section":"D01.01"},
    {"group":"G0003","section":"D01.01"},
    {"group":"G0004","section":"D01.01"},
    {"group":"G0005","section":"D01.01"},
    {"group":"G0006","section":"D01.02"},
    {"group":"G0007","section":"D01.02"},
    {"group":"G0008","section":"D01.02"},
    {"group":"G0009","section":"D01.02"},
    {"group":"G0010","section":"D01.03"},
    {"group":"G0011","section":"D01.03"},
    {"group":"G0012","section":"D01.03"},
    {"group":"G0013","section":"D01.04"},
    {"group":"G0014","section":"D01.04"},
    {"group":"G0015","section":"D01.04"},
    {"group":"G0016","section":"D01.04"},
    {"group":"G0017","section":"D02.01"},
    {"group":"G0018","section":"D02.01"},
    {"group":"G0019","section":"D02.01"},
    {"group":"G0020","section":"D02.01"},
    {"group":"G0021","section":"D02.02"},
    {"group":"G0022","section":"D02.02"},
    {"group":"G0023","section":"D02.02"},
    {"group":"G0024","section":"D02.02"},
    {"group":"G0025","section":"D02.03"},
    {"group":"G0026","section":"D02.03"},
    {"group":"G0027","section":"D02.03"},
    {"group":"G0028","section":"D02.03"},
    {"group":"G0029","section":"D02.04"},
    {"group":"G0030","section":"D02.04"},
    {"group":"G0031","section":"D02.04"},
    {"group":"G0032","section":"D02.04"},
    {"group":"G0033","section":"D02.04"},
    {"group":"G0034","section":"D02.05"},
    {"group":"G0035","section":"D02.05"},
    {"group":"G0036","section":"D02.05"},
    {"group":"G0010","section":"D03.01"},
    {"group":"G0037","section":"D03.01"},
    {"group":"G0038","section":"D03.01"},
    {"group":"G0039","section":"D03.02"},
    {"group":"G0023","section":"D03.02"},
    {"group":"G0040","section":"D03.02"},
    {"group":"G0041","section":"D03.02"},
    {"group":"G0042","section":"D03.03"},
    {"group":"G0043","section":"D03.03"},
    {"group":"G0044","section":"D03.03"},
    {"group":"G0045","section":"D03.04"},
    {"group":"G0046","section":"D03.04"},
    {"group":"G0047","section":"D03.04"},
    {"group":"G0048","section":"D04.01"},
    {"group":"G0049","section":"D04.01"},
    {"group":"G0050","section":"D04.01"},
    {"group":"G0051","section":"D04.02"},
    {"group":"G0052","section":"D04.02"},
    {"group":"G0053","section":"D04.02"},
    {"group":"G0054","section":"D04.03"},
    {"group":"G0055","section":"D04.03"},
    {"group":"G0056","section":"D04.04"},
    {"group":"G0057","section":"D04.04"},
    {"group":"G0058","section":"D04.05"},
    {"group":"G0059","section":"D04.05"},
    {"group":"G0060","section":"D05.01"},
    {"group":"G0061","section":"D05.01"},
    {"group":"G0062","section":"D05.01"},
    {"group":"G0063","section":"D05.01"},
    {"group":"G0064","section":"D05.02"},
    {"group":"G0065","section":"D05.02"},
    {"group":"G0066","section":"D05.02"},
    {"group":"G0067","section":"D05.02"},
    {"group":"G0068","section":"D05.02"},
    {"group":"G0069","section":"D05.03"},
    {"group":"G0070","section":"D05.03"},
    {"group":"G0071","section":"D05.03"},
    {"group":"G0072","section":"D05.04"},
    {"group":"G0073","section":"D05.04"},
    {"group":"G0074","section":"D05.04"},
    {"group":"G0075","section":"D05.05"},
    {"group":"G0076","section":"D05.05"},
    {"group":"G0077","section":"D05.05"},
    {"group":"G0078","section":"D06.01"},
    {"group":"G0079","section":"D06.01"},
    {"group":"G0080","section":"D06.01"},
    {"group":"G0081","section":"D06.02"},
    {"group":"G0082","section":"D06.02"},
    {"group":"G0083","section":"D06.02"},
    {"group":"G0084","section":"D06.03"},
    {"group":"G0085","section":"D06.03"},
    {"group":"G0086","section":"D06.03"},
    {"group":"G0087","section":"D06.04"},
    {"group":"G0088","section":"D06.04"},
    {"group":"G0089","section":"D06.04"},
    {"group":"G0090","section":"D07.01"},
    {"group":"G0091","section":"D07.01"},
    {"group":"G0092","section":"D07.01"},
    {"group":"G0093","section":"D07.01"},
    {"group":"G0094","section":"D07.02"},
    {"group":"G0095","section":"D07.02"},
    {"group":"G0096","section":"D07.02"},
    {"group":"G0097","section":"D07.03"},
    {"group":"G0081","section":"D07.03"},
    {"group":"G0098","section":"D07.03"},
    {"group":"G0099","section":"D07.04"},
    {"group":"G0100","section":"D07.04"},
    {"group":"G0101","section":"D07.04"},
    {"group":"G0102","section":"D07.05"},
    {"group":"G0103","section":"D07.05"},
    {"group":"G0104","section":"D07.05"},
    {"group":"G0105","section":"D08.01"},
    {"group":"G0106","section":"D08.01"},
    {"group":"G0107","section":"D08.01"},
    {"group":"G0108","section":"D08.01"},
    {"group":"G0109","section":"D08.02"},
    {"group":"G0110","section":"D08.02"},
    {"group":"G0111","section":"D08.02"},
    {"group":"G0112","section":"D08.03"},
    {"group":"G0113","section":"D08.03"},
    {"group":"G0114","section":"D08.03"},
    {"group":"G0115","section":"D08.04"},
    {"group":"G0116","section":"D08.04"},
    {"group":"G0117","section":"D08.04"},
    {"group":"G0118","section":"D09.01"},
    {"group":"G0119","section":"D09.01"},
    {"group":"G0120","section":"D09.01"},
    {"group":"G0121","section":"D09.02"},
    {"group":"G0122","section":"D09.02"},
    {"group":"G0123","section":"D09.02"},
    {"group":"G0124","section":"D09.03"},
    {"group":"G0125","section":"D09.03"},
    {"group":"G0126","section":"D09.03"},
    {"group":"G0127","section":"D09.04"},
    {"group":"G0128","section":"D09.04"},
    {"group":"G0129","section":"D10.01"},
    {"group":"G0130","section":"D10.01"},
    {"group":"G0131","section":"D10.01"},
    {"group":"G0132","section":"D10.01"},
    {"group":"G0133","section":"D10.02"},
    {"group":"G0134","section":"D10.02"},
    {"group":"G0135","section":"D10.02"},
    {"group":"G0136","section":"D10.03"},
    {"group":"G0137","section":"D10.03"},
    {"group":"G0138","section":"D10.03"},
    {"group":"G0139","section":"D10.04"},
    {"group":"G0140","section":"D10.04"},
    {"group":"G0141","section":"D10.04"},
    {"group":"G0142","section":"D11.01"},
    {"group":"G0143","section":"D11.01"},
    {"group":"G0144","section":"D11.01"},
    {"group":"G0145","section":"D11.01"},
    {"group":"G0146","section":"D11.02"},
    {"group":"G0147","section":"D11.02"},
    {"group":"G0148","section":"D11.02"},
    {"group":"G0149","section":"D11.03"},
    {"group":"G0150","section":"D11.03"},
    {"group":"G0151","section":"D11.04"},
    {"group":"G0152","section":"D11.04"},
    {"group":"G0153","section":"D11.04"},
    {"group":"G0154","section":"D12.01"},
    {"group":"G0155","section":"D12.01"},
    {"group":"G0043","section":"D12.01"},
    {"group":"G0156","section":"D12.01"},
    {"group":"G0157","section":"D12.02"},
    {"group":"G0158","section":"D12.02"},
    {"group":"G0159","section":"D12.02"},
    {"group":"G0160","section":"D12.03"},
    {"group":"G0161","section":"D12.03"},
    {"group":"G0162","section":"D12.03"},
    {"group":"G0163","section":"D12.04"},
    {"group":"G0164","section":"D12.04"},
    {"group":"G0165","section":"D13.01"},
    {"group":"G0166","section":"D13.01"},
    {"group":"G0167","section":"D13.01"},
    {"group":"G0094","section":"D13.02"},
    {"group":"G0095","section":"D13.02"},
    {"group":"G0168","section":"D13.02"},
    {"group":"G0169","section":"D13.03"},
    {"group":"G0170","section":"D13.03"},
    {"group":"G0171","section":"D13.03"},
    {"group":"G0172","section":"D14.01"},
    {"group":"G0173","section":"D14.01"},
    {"group":"G0174","section":"D14.01"},
    {"group":"G0175","section":"D14.01"},
    {"group":"G0176","section":"D14.01"},
    {"group":"G0177","section":"D14.02"},
    {"group":"G0178","section":"D14.02"},
    {"group":"G0179","section":"D14.02"},
    {"group":"G0180","section":"D14.03"},
    {"group":"G0181","section":"D14.03"},
    {"group":"G0182","section":"D14.04"},
    {"group":"G0183","section":"D14.04"},
    {"group":"G0184","section":"D15.01"},
    {"group":"G0185","section":"D15.01"},
    {"group":"G0106","section":"D15.01"},
    {"group":"G0186","section":"D15.02"},
    {"group":"G0187","section":"D15.02"},
    {"group":"G0188","section":"D15.02"},
    {"group":"G0177","section":"D15.03"},
    {"group":"G0189","section":"D15.03"},
    {"group":"G0190","section":"D15.03"},
    {"group":"G0191","section":"D16.01"},
    {"group":"G0024","section":"D16.01"},
    {"group":"G0192","section":"D16.01"},
    {"group":"G0193","section":"D16.01"},
    {"group":"G0194","section":"D16.02"},
    {"group":"G0195","section":"D16.02"},
    {"group":"G0196","section":"D16.02"},
    {"group":"G0197","section":"D16.03"},
    {"group":"G0198","section":"D16.03"},
    {"group":"G0199","section":"D16.03"},
    {"group":"G0200","section":"D16.04"},
    {"group":"G0201","section":"D16.04"},
    {"group":"G0202","section":"D16.04"},
    {"group":"G0203","section":"D17.01"},
    {"group":"G0204","section":"D17.01"},
    {"group":"G0205","section":"D17.01"},
    {"group":"G0206","section":"D17.02"},
    {"group":"G0207","section":"D17.02"},
    {"group":"G0071","section":"D17.02"},
    {"group":"G0208","section":"D17.03"},
    {"group":"G0209","section":"D17.03"},
    {"group":"G0210","section":"D17.03"},
    {"group":"G0019","section":"D18.01"},
    {"group":"G0211","section":"D18.01"},
    {"group":"G0212","section":"D18.01"},
    {"group":"G0213","section":"D18.02"},
    {"group":"G0214","section":"D18.02"},
    {"group":"G0215","section":"D18.02"},
    {"group":"G0216","section":"D18.03"},
    {"group":"G0217","section":"D18.03"},
    {"group":"G0218","section":"D19.01"},
    {"group":"G0219","section":"D19.01"},
    {"group":"G0220","section":"D19.01"},
    {"group":"G0221","section":"D19.02"},
    {"group":"G0222","section":"D19.02"},
    {"group":"G0223","section":"D19.02"},
    {"group":"G0044","section":"D20.01"},
    {"group":"G0224","section":"D20.01"},
    {"group":"G0225","section":"D20.01"},
    {"group":"G0226","section":"D20.02"},
    {"group":"G0227","section":"D20.02"},
    {"group":"G0228","section":"D20.02"},
    {"group":"G0229","section":"D20.03"},
    {"group":"G0230","section":"D20.03"},
    {"group":"G0231","section":"D20.03"},
    {"group":"G0232","section":"D21.01"},
    {"group":"G0004","section":"D21.01"},
    {"group":"G0233","section":"D21.01"},
    {"group":"G0099","section":"D21.02"},
    {"group":"G0234","section":"D21.02"},
    {"group":"G0235","section":"D21.03"},
    {"group":"G0236","section":"D21.03"},
    {"group":"G0237","section":"D22.01"},
    {"group":"G0238","section":"D22.01"},
    {"group":"G0239","section":"D22.01"},
    {"group":"G0240","section":"D22.02"},
    {"group":"G0234","section":"D22.02"},
    {"group":"G0241","section":"D22.03"},
    {"group":"G0242","section":"D22.03"},
    {"group":"G0243","section":"D22.03"},
    {"group":"G0048","section":"D23.01"},
    {"group":"G0051","section":"D23.01"},
    {"group":"G0244","section":"D23.01"},
    {"group":"G0058","section":"D23.01"},
    {"group":"G0021","section":"D23.02"},
    {"group":"G0023","section":"D23.02"},
    {"group":"G0039","section":"D23.02"},
    {"group":"G0045","section":"D23.03"},
    {"group":"G0245","section":"D23.03"},
    {"group":"G0246","section":"D23.03"}
  ],
  secCats: [
    {"group":"G0169","cat":"C04"},
    {"group":"G0186","cat":"C01"},
    {"group":"G0200","cat":"C04"}
  ]
  };
})();
